### ISSUE TITLE
Train-time

### ISSUE THREAD

**Issue by xjywhu** [nouhadziri/THRED#14]
We have used the dataset which is 5 turns per line, and the num of gpus is 2, however the result of the command line is number of gup 0, and the speed of the training is very low. We estimate that it will take one month to complete the training of the model. I want to ask whether the speed of training is normal and how to accelerate the training.
![image](https://user-images.githubusercontent.com/43105182/60933398-a4ac8380-a2f4-11e9-9741-20dbdad0fce2.png)

**Comment by xjywhu** [comment]
Can the model support Chinese?

**Comment by ehsk** [comment]
Thanks for your interest in our work.

Based on what I'm seeing in the screenshot you sent, seems you have installed the CPU version of TensorFlow because no GPUs are detected in the list of devices. You can test this by running `pip freeze` (or `conda list` if you're using Anaconda) and checking which TensorFlow has been set up. You can also check the devices in the Python shell:
```python3
from tensorflow.python.client import device_lib
device_lib.list_local_devices()
```
The above function returns all the visible devices. Please make sure that the GPUs are listed in the output.

The training on the 3-turn data takes about 2 weeks to complete using 2 GPUs.

All models presented here are language independent. As long as the data format is ok, any data can be fed to this framework.

**Comment by xjywhu** [comment]
Thank you for replying my question. And I want to ask when the pretrained model would be presented on GitHub.

**Comment by ehsk** [comment]
We will release the pre-trained models very soon. Stay tuned!
